//report to suttacentral/sc-data/issues#74

 "word": "jimha",
 	 '(cp. vanka, opp. uju |','(cp. vanka, opp. uju )'
 	 

        "word": "māsati",
        "text": "<dl id='māsati'><dt><dfn>Māsati, Māsana, Māsin</dfn></dt><dd><p><span class='square'>■</span> dumapakkāni <i class='term'>-māsita</i> <span class='ref'>Ja.ii.446</span> (C. reads māsita & explains by asita, dhāta); visa-māsita <span class='ref'>Mil.302</span> (T. reads visamāsita) having taken in poison; visa- <i class='term'>māsan-</i> ûpatāpa (id.) <span class='ref'>Vism.166</span>; tiṇa <i class='term'>-māsin</i> eating grass <span class='ref'>Ja.vi.354</span> (= tiṇakhādaka C.)<br><span class='square'>■</span> A similar case where Sandhi-m-has led to a wrong partition of syllables and has thus been lost through syncope may be P. eḷaka<sup>1</sup>, as comp<sup>d</sup> with Sk. methi (cp. Prk. meḍhi), pillar, post.</p><p class='eti'>fr. <i class='term'>mṛṣ</i>, for massati etc.; see <i class='term'><a href='/define/masati'>masati</a></i>| touch, touching, etc. in sense of eating or taking in. So is probably to be read for āsati etc. in the foll. passages, where <i class='term'>m</i> precedes this <i class='term'><a href='/define/ā'>ā</a></i> in all cases Otherwise we have to refer them to a root <i class='term'>ās = as</i> (to eat) and consider the <i class='term'>m</i> as partly euphonic.</p></dd></dl>"
        	
        	
        "word": "māsati",
        "text": "<dl id='māsati'><dt><dfn>Māsati, Māsana, Māsin</dfn></dt><dd><p>touch, touching, etc. in sense of eating or taking in. So is probably to be read for āsati etc. in the foll. passages, where <i class='term'>m</i> precedes this <i class='term'><a href='/define/ā'>ā</a></i> in all cases Otherwise we have to refer them to a root <i class='term'>ās = as</i> (to eat) and consider the <i class='term'>m</i> as partly euphonic.</p><span class='square'>■</span> dumapakkāni <i class='term'>-māsita</i> <span class='ref'>Ja.ii.446</span> (C. reads māsita & explains by asita, dhāta); visa-māsita <span class='ref'>Mil.302</span> (T. reads visamāsita) having taken in poison; visa- <i class='term'>māsan-</i> ûpatāpa (id.) <span class='ref'>Vism.166</span>; tiṇa <i class='term'>-māsin</i> eating grass <span class='ref'>Ja.vi.354</span> (= tiṇakhādaka C.)<br><span class='square'>■</span> A similar case where Sandhi-m-has led to a wrong partition of syllables and has thus been lost through syncope may be P. eḷaka<sup>1</sup>, as comp<sup>d</sup> with Sk. methi (cp. Prk. meḍhi), pillar, post.</p><p class='eti'>fr. <i class='term'>mṛṣ</i>, for massati etc.; see <i class='term'><a href='/define/masati'>masati</a></i></p> </dd></dl>"